[project]
name = "tp-drf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ignacio97", email = "i.pineiro@itecriocuarto.org.ar" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.0",
]

[project.scripts]
tp-drf = "tp_drf:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
