# Generated by Django 6.1.1 on 2026-09-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
